### ISSUE TITLE
Broken link to xml-validator command-line tool

### ISSUE THREAD

**Issue by osgraf1** [ISAITB/xml-validator#1]
The command-line tool link "https://www.itb.ec.europa.eu/xml-offline/any/validator.zip" i broken. Is there an alternative URL?

**Comment by costas80** [comment]
Hi @osgraf1. Thanks for bringing this to our attention. The correct link for the validator's CLI tool is in fact https://www.itb.ec.europa.eu/xml-offline/xml/validator.zip (note the `xml` instead of `any`). The README link has now been updated to use the correct URL.

Don't hesitate to let me know if you have any further issues.

**Comment by osgraf1** [comment]
Thanks @costas80! Problem seems to be resolved! :-)
